# Generated by Django 4.0.5 on 2022-06-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_userusagesituation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userusagesituation',
            name='display_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userusagesituation',
            name='research_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
